- greeting:
    text_size: xl
    text: My Media Server
- resources: 
    label: System
    expanded: true 
    cpu: true 
    memory: true 
    uptime: true 

- resources:
    label: Storage - CachyOS
    disk:
      - /

- resources:
    label: Storage - Media
    disk:
     - /mnt/media_disk

- resources:
    label: Storage - Crucial500 SSD
    disk:
     - /mnt/scratch_disk


